using System.ComponentModel;
using System.Xml.Linq;

namespace OpenDocumentCreator.Styles;

/// <summary>
/// The style:page-layout element represents the styles that specify the formatting properties
/// of a page.
///
/// See: 16.5
/// </summary>
public class OpenDocumentPageLayout : OpenDocumentWritable
{
    /// <inheritdoc />
    internal override string OpenDocumentElementName => "page-layout";

    /// <inheritdoc />
    internal override string? NamespaceName => "style";

    /// <summary>
    /// The style:name attribute specifies the name of a page layout.
    /// </summary>
    /// <remarks>
    /// For automatic styles, the name may be generated by OpenDocument producers. For each style
    /// family or style element, producers should generate distinct sets of names for automatic styles
    /// stored in the content.xml 3.1.3.2 and styles.xml 3.1.3.3 files. The names should also be distinct
    /// from the names used in the office:styles element inside the styles.xml files.
    ///
    /// Note: If the document is produced multiple times, it cannot be assumed that the same name is
    /// generated each time.
    /// </remarks>
    [OpenDocumentName("name", ElemNamespace = "style")]
    public string? Name { get; set; } = null;

    /// <summary>
    /// The style:page-layout-properties element acts as a container for attributes and
    /// elements that define a page layout.
    /// </summary>
    [OpenDocumentName]
    public OpenDocumentPageLayoutProperties? PageLayoutProperties { get; set; } = null;

    /// <summary>
    /// The style:header-style element specifies the formatting properties for a header element.
    /// </summary>
    [OpenDocumentName]
    public OpenDocumentHeaderStyle? HeaderStyle { get; set; } = null;

    /// <summary>
    /// The style:footer-style element specifies the formatting properties for a footer element.
    /// </summary>
    [OpenDocumentName]
    public OpenDocumentFooterStyle? FooterStyle { get; set; } = null;
}
